### ISSUE TITLE
redirect empty path to /flashcards

### ISSUE THREAD

**Issue by annbgn** [annbgn/duolingo_flashcards#23]
add redirect

**Comment by CS-Aditya-Rawat** [comment]
I send a pull request for this issue I fixed it.

**Comment by annbgn** [comment]
in my request i leave `/flashcards` as an option also

**Comment by CS-Aditya-Rawat** [comment]
Is you merged my pull request this is my first time contributing to another project on Github, but my name is not showing as contributors in the project? why this is happening

**Comment by annbgn** [comment]
no, i didn't like your solution, so i made my own and closed the issue.
now as i think of it, it's is easier for me to work on my project alone then wasting energy on talking, so i'm gonna make the repo private
